name: PaperMcRunner
version: '${project.version}'
main: com.greenjon902.hisdoc.runners.papermc.HisDocRunner
api-version: '1.20'

commands:
  addevent:
    usage: /<command> [--ignore-ip]
    permission: hisdoc.addevent

permissions:
  hisdoc.addevent:
