name: HisDocPaperMcRunner
version: '${project.version}'
main: com.greenjon902.hisdoc.runners.papermc.HisDocRunner
api-version: '1.20'

libraries:
  - mysql:mysql-connector-java:8.0.33
  - org.apache.commons:commons-text:1.10.0
  - io.quickchart:QuickChart:1.2.0

commands:
  hisdoc:
    aliases: [hs]

permissions:
  hisdoc.link:
    default: op
    description: Should this person be able to link their accound and add events

  hisdoc.restart:
    default: op

  hisdoc.hisdoc.editevent:
    default: op
    description: Should this person be able to edit events
