name: HisDocPaperMcRunner
version: '${project.version}'
main: com.greenjon902.hisdoc.runners.papermc.HisDocRunner
api-version: '1.20'

libraries:
  - mysql:mysql-connector-java:8.0.33
  - org.apache.commons:commons-text:1.10.0
  - io.quickchart:QuickChart:1.2.0

commands:
  addevent:
    usage: /<command> [--ignore-ip]
    permission: hisdoc.addevent

  restarthisdoc:
    usage: /<command> [confirm]
    permission: hisdoc.restart

permissions:
  hisdoc.addevent:
    default: op
    description: Should this person be able to add events

  hisdoc.addevent.ingoreip:
    default: op
    description: Should this person be able to add events while using a different IP to that which minecraft is on

  hisdoc.addevent.persist:
    default: op
    description: Should this person be able to add events with the same code multiple times

  hisdoc.restart:
    default: op
